import * as React from 'react';
import { Trans } from 'react-i18next';
import { Alert, Button, Modal, ModalBody, ModalFooter, ModalHeader, Stack, StackItem } from '@patternfly/react-core';

import { useTranslation } from '../../../hooks/useTranslation';
import { useFetch } from '../../../hooks/useFetch';
import { getErrorMessage } from '../../../utils/error';

const DeleteImageBuildModal = ({
  imageBuildId,
  onClose,
}: {
  imageBuildId: string;
  onClose: (hasDeleted?: boolean) => void;
}) => {
  const { t } = useTranslation();
  const { remove } = useFetch();

  const [error, setError] = React.useState<{ text: string; details?: string }>();
  const [isDeleting, setIsDeleting] = React.useState<boolean>();

  const onDelete = async () => {
    try {
      // CELIA-WIP: we need to delete the associated imageExports, or would the API do it for us?
      await remove(`imagebuilds/${imageBuildId}`);
    } catch (imageBuildErr) {
      setError({
        text: t('Deletion of image build {{imageBuildId}} failed.'),
        details: getErrorMessage(imageBuildErr),
      });
    }
  };

  return (
    <Modal
      isOpen
      onClose={() => {
        onClose();
      }}
      variant="small"
    >
      <ModalHeader title={t('Delete image build?')} titleIconVariant="warning" />
      <ModalBody>
        <Stack hasGutter>
          <StackItem>
            <Alert variant="info" title={t('Note about generated images')} isInline>
              {t('Deleting this image build will not affect any of the images generated by it.')}
            </Alert>
          </StackItem>
          <StackItem>
            <Trans t={t}>
              <strong>{imageBuildId}</strong> will be deleted permanently. This action cannot be undone.
            </Trans>
          </StackItem>
          <StackItem>{t('Are you sure you want to delete?')}</StackItem>
          {error && (
            <StackItem>
              <Alert isInline variant="danger" title={t('An error occurred')}>
                <div>{error.text}</div>
                {error.details && <div>{t('Details: {{errorDetails}}', { errorDetails: error.details })}</div>}
              </Alert>
            </StackItem>
          )}
        </Stack>
      </ModalBody>
      <ModalFooter>
        <Button
          key="confirm"
          variant="danger"
          isDisabled={isDeleting || !!error}
          isLoading={isDeleting}
          onClick={async () => {
            setError(undefined);
            try {
              setIsDeleting(true);
              await onDelete();
              setIsDeleting(false);
              onClose(true);
            } catch {
              setIsDeleting(false);
            }
          }}
        >
          {t('Delete image build')}
        </Button>
        <Button
          key="cancel"
          variant="link"
          onClick={() => {
            onClose();
          }}
          isDisabled={isDeleting}
        >
          {t('Cancel')}
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default DeleteImageBuildModal;
