import * as React from 'react';
import { Alert, Button, Progress, ProgressMeasureLocation, Stack, StackItem } from '@patternfly/react-core';
import { Modal, ModalBody, ModalFooter, ModalHeader } from '@patternfly/react-core/next';
import { Table, Tbody, Td, Th, Thead, Tr } from '@patternfly/react-table';

import { ImagePipelineResponse } from '@flightctl/types/imagebuilder';
import { getErrorMessage } from '../../../../utils/error';
import { useFetch } from '../../../../hooks/useFetch';
import { useTranslation } from '../../../../hooks/useTranslation';
import { isPromiseRejected } from '../../../../types/typeUtils';
import { getImageBuildDestinationImage, getImageBuildSourceImage } from '../../../../utils/imageBuilds';

type MassDeleteImageBuildModalProps = {
  onClose: VoidFunction;
  imagePipelines: Array<ImagePipelineResponse>;
  onDeleteSuccess: VoidFunction;
};

const MassDeleteImageBuildTable = ({ imagePipelines }: { imagePipelines: Array<ImagePipelineResponse> }) => {
  const { t } = useTranslation();
  return (
    <Table>
      <Thead>
        <Tr>
          <Th modifier="fitContent">{t('Name')}</Th>
          <Th modifier="fitContent">{t('Base image')}</Th>
          <Th modifier="fitContent">{t('Output image')}</Th>
        </Tr>
      </Thead>
      <Tbody>
        {imagePipelines.map((pipeline) => {
          const imageBuild = pipeline.imageBuild;
          const name = imageBuild.metadata.name || '';
          const baseImage = getImageBuildSourceImage(imageBuild);
          const outputImage = getImageBuildDestinationImage(imageBuild);
          return (
            <Tr key={name}>
              <Td dataLabel={t('Name')}>{name}</Td>
              <Td dataLabel={t('Base image')}>{baseImage}</Td>
              <Td dataLabel={t('Output image')}>{outputImage}</Td>
            </Tr>
          );
        })}
      </Tbody>
    </Table>
  );
};

// CELIA-WIP: we need copy from UX designers
const MassDeleteImageBuildModal = ({ onClose, imagePipelines, onDeleteSuccess }: MassDeleteImageBuildModalProps) => {
  const { t } = useTranslation();
  const [progress, setProgress] = React.useState(0);
  const [progressTotal, setProgressTotal] = React.useState(0);
  const [isDeleting, setIsDeleting] = React.useState(false);
  const [errors, setErrors] = React.useState<string[]>();
  const { remove } = useFetch();

  const deleteImagePipelines = async () => {
    setProgress(0);
    setIsDeleting(true);
    const promises = imagePipelines.map(async (p) => {
      // Deleting an image pipeline will delete both the imageBuild and any associated imageExport
      await remove(`imagepipelines/${p.imageBuild.metadata.name}`);
      setProgress((p) => p + 1);
    });

    setProgressTotal(promises.length);
    const results = await Promise.allSettled(promises);
    setIsDeleting(false);

    const rejectedResults = results.filter(isPromiseRejected);

    if (rejectedResults.length) {
      setErrors(rejectedResults.map((r) => getErrorMessage(r.reason)));
    } else {
      onDeleteSuccess();
    }
  };

  return (
    <Modal isOpen onClose={isDeleting ? undefined : onClose} variant="medium">
      <ModalHeader title={t('Delete image builds ?')} titleIconVariant="warning" />
      <ModalBody>
        <Stack hasGutter>
          <StackItem>
            <Alert variant="info" title={t('Note about generated images')} isInline>
              {t('Deleting image builds will not affect any of the images generated by them.')}
            </Alert>
          </StackItem>
          <StackItem>
            <MassDeleteImageBuildTable imagePipelines={imagePipelines} />
          </StackItem>

          {isDeleting && (
            <StackItem>
              <Progress
                value={progress}
                min={0}
                max={progressTotal}
                title={t('Deleting...')}
                measureLocation={ProgressMeasureLocation.top}
                label={t('{{progress}} of {{progressTotal}}', { progress, progressTotal })}
                valueText={t('{{progress}} of {{progressTotal}}', { progress, progressTotal })}
              />
            </StackItem>
          )}
          {errors?.length && (
            <StackItem>
              <Alert isInline variant="danger" title={t('An error occurred')}>
                <Stack hasGutter>
                  {errors.map((e, index) => (
                    <StackItem key={index}>{e}</StackItem>
                  ))}
                </Stack>
              </Alert>
            </StackItem>
          )}
        </Stack>
      </ModalBody>
      <ModalFooter>
        <Button
          key="delete"
          variant="danger"
          onClick={deleteImagePipelines}
          isLoading={isDeleting}
          isDisabled={isDeleting}
        >
          {t('Delete image builds')}
        </Button>
        <Button key="cancel" variant="link" onClick={onClose} isDisabled={isDeleting}>
          {t('Cancel')}
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default MassDeleteImageBuildModal;
