import * as React from 'react';
import {
  Alert,
  Breadcrumb,
  BreadcrumbItem,
  Bullseye,
  PageSection,
  PageSectionVariants,
  Spinner,
  Title,
  Wizard,
  WizardStep,
  WizardStepType,
} from '@patternfly/react-core';
import { Formik, FormikErrors } from 'formik';

import { RepoSpecType, RepositoryList } from '@flightctl/types';
import { ImagePipelineRequest } from '@flightctl/types/imagebuilder';
import { RESOURCE, VERB } from '../../../types/rbac';
import { useFetch } from '../../../hooks/useFetch';
import { useTranslation } from '../../../hooks/useTranslation';
import { useFetchPeriodically } from '../../../hooks/useFetchPeriodically';
import { Link, ROUTE, useNavigate } from '../../../hooks/useNavigate';

import ReviewStep, { reviewStepId } from './steps/ReviewStep';
import { getErrorMessage } from '../../../utils/error';
import { getImagePipelineResource, getInitialValues, getValidationSchema } from './utils';
import { ImageBuildFormValues } from './types';
import LeaveFormConfirmation from '../../common/LeaveFormConfirmation';
import ErrorBoundary from '../../common/ErrorBoundary';
import PageWithPermissions from '../../common/PageWithPermissions';
import { usePermissionsContext } from '../../common/PermissionsContext';
import SourceImageStep, { isSourceImageStepValid, sourceImageStepId } from './steps/SourceImageStep';
import ImageOutputStep, { isOutputImageStepValid, outputImageStepId } from './steps/OutputImageStep';
import RegistrationStep, { isRegistrationStepValid, registrationStepId } from './steps/RegistrationStep';
import CreateImageBuildWizardFooter from './CreateImageBuildWizardFooter';

const orderedIds = [sourceImageStepId, outputImageStepId, registrationStepId, reviewStepId];

const getValidStepIds = (formikErrors: FormikErrors<ImageBuildFormValues>): string[] => {
  const validStepIds: string[] = [];
  if (isSourceImageStepValid(formikErrors)) {
    validStepIds.push(sourceImageStepId);
  }
  if (isOutputImageStepValid(formikErrors)) {
    validStepIds.push(outputImageStepId);
  }
  if (isRegistrationStepValid(formikErrors)) {
    validStepIds.push(registrationStepId);
  }
  // Review step is always valid. We disable it if some of the previous steps are invalid
  if (validStepIds.length === orderedIds.length - 1) {
    validStepIds.push(reviewStepId);
  }
  return validStepIds;
};

const isDisabledStep = (stepId: string | undefined, validStepIds: string[]) => {
  if (!stepId) {
    return true;
  }

  const stepIdx = orderedIds.findIndex((stepOrderId) => stepOrderId === stepId);

  return orderedIds.some((orderedId, orderedStepIdx) => {
    return orderedStepIdx < stepIdx && !validStepIds.includes(orderedId);
  });
};

const CreateImageBuildWizard = () => {
  const { t } = useTranslation();
  const { post } = useFetch();
  const [error, setError] = React.useState<unknown>();
  const navigate = useNavigate();
  const [currentStep, setCurrentStep] = React.useState<WizardStepType>();
  const [repoList, isLoading, repoError, refetchRepositories] = useFetchPeriodically<RepositoryList>({
    endpoint: 'repositories',
  });

  // CELIA-WIP: Use RepoSpecType.OCI when OCI repositories are available
  const ociRegistries = (repoList?.items || []).filter((repo) => repo.spec.type === RepoSpecType.HTTP);

  return (
    <>
      <PageSection variant="light" type="breadcrumb">
        <Breadcrumb>
          <BreadcrumbItem>
            <Link to={ROUTE.IMAGE_BUILDS}>{t('Image builds')}</Link>
          </BreadcrumbItem>
          <BreadcrumbItem isActive>{t('Build new image')}</BreadcrumbItem>
        </Breadcrumb>
      </PageSection>
      <PageSection variant={PageSectionVariants.light}>
        <Title headingLevel="h1" size="3xl">
          {t('Build new image')}
        </Title>
      </PageSection>
      <PageSection variant={PageSectionVariants.light} type="wizard">
        <ErrorBoundary>
          {isLoading ? (
            <Bullseye>
              <Spinner />
            </Bullseye>
          ) : repoError ? (
            <Alert isInline variant="danger" title={t('An error occurred')}>
              {getErrorMessage(repoError)}
            </Alert>
          ) : (
            <Formik<ImageBuildFormValues>
              initialValues={getInitialValues()}
              validationSchema={getValidationSchema(t)}
              validateOnMount
              onSubmit={async (values) => {
                setError(undefined);
                try {
                  const request = getImagePipelineResource(values);
                  await post<ImagePipelineRequest>('imagepipelines', request);
                  navigate({
                    route: ROUTE.IMAGE_BUILD_DETAILS,
                    // The name was autogenerated by us
                    postfix: request.imageBuild.metadata.name,
                  });
                } catch (e) {
                  setError(getErrorMessage(e));
                }
              }}
            >
              {({ errors: formikErrors }) => {
                const validStepIds = getValidStepIds(formikErrors);

                // CELIA-WIP: Remove "allStepIds" once the validation is implemented
                // Temporarily allow all steps to be enabled for navigation
                const allStepIds = formikErrors ? orderedIds : validStepIds;

                return (
                  <>
                    <LeaveFormConfirmation />
                    <Wizard
                      footer={<CreateImageBuildWizardFooter />}
                      onStepChange={(_, step) => {
                        if (error) {
                          setError(undefined);
                        }
                        setCurrentStep(step);
                      }}
                    >
                      <WizardStep name={t('Image details')} id={sourceImageStepId}>
                        {(!currentStep || currentStep?.id === sourceImageStepId) && (
                          <SourceImageStep repositories={ociRegistries} repoRefetch={refetchRepositories} />
                        )}
                      </WizardStep>
                      <WizardStep
                        name={t('Image output')}
                        id={outputImageStepId}
                        isDisabled={isDisabledStep(outputImageStepId, allStepIds)}
                      >
                        {currentStep?.id === outputImageStepId && (
                          <ImageOutputStep repositories={ociRegistries} repoRefetch={refetchRepositories} />
                        )}
                      </WizardStep>
                      <WizardStep
                        name={t('Registration')}
                        id={registrationStepId}
                        isDisabled={isDisabledStep(registrationStepId, allStepIds)}
                      >
                        {currentStep?.id === registrationStepId && <RegistrationStep />}
                      </WizardStep>
                      <WizardStep
                        name={t('Review')}
                        id={reviewStepId}
                        isDisabled={isDisabledStep(reviewStepId, allStepIds)}
                      >
                        {currentStep?.id === reviewStepId && <ReviewStep error={error} repositories={ociRegistries} />}
                      </WizardStep>
                    </Wizard>
                  </>
                );
              }}
            </Formik>
          )}
        </ErrorBoundary>
      </PageSection>
    </>
  );
};

const createImageBuildWizardPermissions = [{ kind: RESOURCE.IMAGE_BUILD, verb: VERB.CREATE }];

const CreateImageBuildWizardWithPermissions = () => {
  const { checkPermissions, loading } = usePermissionsContext();
  const [createAllowed] = checkPermissions(createImageBuildWizardPermissions);
  return (
    <PageWithPermissions allowed={createAllowed} loading={loading}>
      <CreateImageBuildWizard />
    </PageWithPermissions>
  );
};

export default CreateImageBuildWizardWithPermissions;
