name: Create UI version update PR in flightctl

on:
  release:
    types:
      - published

jobs:
  update-flightctl-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: celdrake/flightctl
          ref: main

      - name: Get image tag
        id: get-tags
        run: |
          helm_tag=( ${{ github.ref_name }} )
          helm_tag=${image_tag#v} # remove the leading v prefix for version
          echo "HELM_TAG=${helm_tag}" >> $GITHUB_ENV
          echo "HELM_TAG1=${helm_tag}"

      - name: Update the helm dependency in flightctl
        run: |
          echo "HELM_TAG2=${helm_tag}"
          git checkout -b update-ui-to-last-release
          cd deploy/helm/flightctl
          sed -i -r -e  '/name: flightctl-ui/ { n;n; s/version: (.*)/version: "${{ env.HELM_TAG }}"/ }' Chart.yaml
          helm dependency update
          git add Chart.yaml Chart.lock
          git commit -m "Update UI dependency to v${{ env.HELM_TAG }}"

      - name: Create the PR in flightctl repository
        if: ${{ github.event.release.target_commitish == 'skip-this' }}
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          commit-message: Test Update UI to Version ${{ env.HELM_TAG }}
          committer: GitHub action executed on release <noreply@github.com>
          author: GitHub action executed on release <noreply@github.com>
          title: Test Update UI to Version ${{ env.HELM_TAG }}
          body:
            Triggered by new UI tag - https://github.com/flightctl/flightctl-ui/releases/tag/v${{ env.HELM_TAG }}
