name: Create UI version update PR in flightctl

on:
  release:
    types:
      - published

jobs:
  update-flightctl-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: celdrake/flightctl
          ref: main

      - name: Get helm tag
        id: get-tag
        run: |
          helm_tag=( ${{ github.ref_name }} )
          helm_tag=${helm_tag#v} # remove the leading v prefix for version
          echo "HELM_TAG=${helm_tag}" >> $GITHUB_ENV

      - name: Update the helm dependency in flightctl
        run: |
          echo "HELM_TAG=${{ env.HELM_TAG }}"
          git checkout -b update-ui-to-last-release
          cd deploy/helm/flightctl
          sed -i -r -e  '/name: flightctl-ui/ { n;n; s/version: (.*)/version: "${{ env.HELM_TAG }}"/ }' Chart.yaml
          helm dependency update
          git add Chart.yaml Chart.lock

          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -m "Update UI dependency to v${{ env.HELM_TAG }}"
          git push origin update-ui-to-last-release

      - name: Create the PR in flightctl repository
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          commit-message: (IGNORE_THIS) Update UI to ${{ github.ref_name }}
          committer: GitHub action executed on UI release <noreply@github.com>
          author: GitHub action executed on UI release <noreply@github.com>
          title: (IGNORE_THIS) Update UI to ${{ github.ref_name }}
          body:
            Triggered by new UI release - https://github.com/flightctl/flightctl-ui/releases/tag/${{ github.ref_name }}
