name: Release a new version

on:
  release:
    types:
      - created

jobs:
  update-flightctl-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Check release tag
        run: |
          if [[ "${{ github.event.release.target_commitish }}" != *releases* ]]; then
            echo "Expecting to be in a release branch, but we are in: ${{ github.event.release.target_commitish }}"
            exit 1
          fi

      - uses: actions/checkout@v3
        with:
          repository: https://github.com/celdrake/flightctl
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Update the helm dependency in flightctl
        run: |
          git checkout -b update-ui-to-last-release
          cd deploy/helm/flightctl
          helm dependency update
          git add .
          git commit -m "Update UI version to Version ${GITHUB_REF_NAME}"

      - name: Create the PR in flightctl repository
        if: ${{ github.event.release.target_commitish == 'skip-this' }}
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          commit-message: Test Update UI to Version ${{ github.ref_name }}
          committer: GitHub action executed on release <noreply@github.com>
          author: GitHub action executed on release <noreply@github.com>
          title: Test Update UI to Version ${{ github.ref_name }}
          body:
            Triggered by new UI tag - https://github.com/flightctl/flightctl-ui/releases/tag/v$${{ github.ref_name }}
